title: "Mason Tatafu's Portfolio"
description: "Welcome to my personal website"
author: "Mason Tatafu"
force_build: true

markdown: kramdown
theme: null
exclude: 
  - README.md
  - LICENSE
  - node_modules
  - Gemfile
  - Gemfile.lock

plugins: 
  - jekyll-seo-tag
  - jekyll-sitemap

