title: "Mason Tatafu's Portfolio"
description: "Welcome to my personal website"
author: "Mason Tatafu"
include:
  - assets

markdown: kramdown
theme: null
exclude: 
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock

plugins: 
  - jekyll-seo-tag
  - jekyll-sitemap

