theme: null  # Disables GitHub's default theme so we use our custom styles
markdown: kramdown  # Ensures Markdown processing works correctly
include:
  - _layouts  # Ensures GitHub Pages includes the layout files
  - assets  # Ensures the assets folder is processed
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
